### PR TITLE
Added function attractors_with_basins and added comment on attractors function

### PR DESCRIPTION
**Pull request by hbsmith**

### CODE REVIEW

**Comment by siyuzhou** [comment]
I think the goal is to change functions `attractors` and `basins` so that their outputs are naturally ordered the same way?

**Comment by hbsmith** [comment]
If you're interested in getting both the attractor and basin outputs anyway, then it's easier to pair them up as part of a single function which outputs both than to try and modify attractors and basins individually. In cases where you're only interested in either the attractors or basins, it doesn't matter if they match up anyways. That's my perspective at least.

**Comment by siyuzhou** [comment]
I see your point. I would argue with respect that this function does not offer practical improvement. `attractors_with_basins` is just a wrapper with a `for` loop, and in cases where you do need all basins with their corresponding attractors, you still need a `for` loop through the return of this function. Instead of doing
```python
for attractor, basin in attractors_with_basins(net):
    ...
```
users could do the following anyway,
```python
for basin in basins(net):
    attractor = attractors(basin)
    ...
```
The performance would be the same.
I feel this would clutter our interface without meaningful gain. It's just my thought though. :)

**Comment by hbsmith** [comment]
That's a fair point. There's not a performance loss for using this `attractors_with_basins` function, so I think it comes down to if anyone would prefer this to your example of:

    for basin in basins(net):
        attractor = attractors(basin)
        ...

The one annoying part with the above is that `attractors` returns a generator of lists of lists, so in order to get the actual attractor lists for each basin you'd have to call:
    
    for basin in basins(net):
       attractor =  list(neet.synchronous.attractors(basin))[0]

I appreciate your feedback though--no rush to merge this if we decide it's superfluous.

**Comment by dglmoore** [comment]
@bcdaniels What do you think?

**Comment by bcdaniels** [comment]
No strong opinion, but I think I side with Siyu.  As a user I don't want to be bothered to think about whether things are ordered or not, and I would be annoyed if I assumed they were ordered in the same way and then found out they weren't by digging into the documentation.  So I think we should aim to have basins and attractors ordered in the same way (in which case this new function would be superfluous?).

Note that with Doug's new work we might soon have our own implementation of these functions, in which case it would presumably be easy to order things.

**Pull request closed without merging**
