### PR TITLE
Added LogicNetwork class

### PR DESCRIPTION
**Pull request by siyuzhou**
LogicNetwork can now update net state with a truth table. `classmethod` attribute `read_table` remains to be implemented.

### CODE REVIEW

**Comment by siyuzhou** [comment]
Didn't pass automated test. Closed.

**Comment by siyuzhou** [comment]
Strange. All unit tests passed locally.

**Comment by siyuzhou** [comment]
After digging into the errors, it looks like `test_interface.py` was changed back to a stage when it was still importing from `landscape.py`. The current branch I am working on for logic update has the latest structure.

**Comment by siyuzhou** [comment]
Conflicts resolved, hopefully... Reopening.

**Comment by dglmoore** [comment]
@siyuzhou I'll take a look at this and #46 this evening. Thanks for working on them!

**Comment by dglmoore** [comment]
Sorry, hot the wrong button!

**Pull request merged**
